// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * SaveAIConfig 将 apiKey、apiUrl、modelName 保存到本地密钥存储（管道分隔）。
 */
export function SaveAIConfig(apiKey: string, apiUrl: string, modelName: string): $CancellablePromise<void> {
    return $Call.ByID(2210810222, apiKey, apiUrl, modelName);
}
