// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CancelDataMigrationJob(jobID: string): $CancellablePromise<void> {
    return $Call.ByID(3268196905, jobID);
}

export function CancelRunningQuery(req: $models.CancelRunningQueryRequest): $CancellablePromise<void> {
    return $Call.ByID(3091379923, req);
}

export function DeleteRows(req: $models.DeleteRowsRequest): $CancellablePromise<$models.SQLExecutionResult> {
    return $Call.ByID(1246682378, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ExecuteSQL(req: $models.ExecuteSQLRequest): $CancellablePromise<$models.SQLExecutionResult> {
    return $Call.ByID(1085282957, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ExplainSQL(req: $models.ExplainSQLRequest): $CancellablePromise<$models.SQLExecutionResult> {
    return $Call.ByID(3388748133, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetDataMigrationJob(jobID: string): $CancellablePromise<$models.DataMigrationJobSnapshot> {
    return $Call.ByID(725792143, jobID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetTableSchema(req: $models.TableSchemaRequest): $CancellablePromise<$models.TableSchema> {
    return $Call.ByID(1557858719, req).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * HasRunningMigration returns true if any migration job is currently running.
 */
export function HasRunningMigration(): $CancellablePromise<boolean> {
    return $Call.ByID(3824549157);
}

export function InsertRows(req: $models.InsertRowsRequest): $CancellablePromise<$models.SQLExecutionResult> {
    return $Call.ByID(2045419812, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ListDatabases(connectionID: string): $CancellablePromise<$models.SchemaObject[]> {
    return $Call.ByID(4087710774, connectionID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ListIndexes(connectionID: string, database: string, schema: string, table: string): $CancellablePromise<$models.SchemaObject[]> {
    return $Call.ByID(3901981548, connectionID, database, schema, table).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ListSchemas(connectionID: string, database: string): $CancellablePromise<$models.SchemaObject[]> {
    return $Call.ByID(2893177596, connectionID, database).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ListTables(connectionID: string, database: string, schema: string): $CancellablePromise<$models.SchemaObject[]> {
    return $Call.ByID(4175186377, connectionID, database, schema).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ListViews(connectionID: string, database: string, schema: string): $CancellablePromise<$models.SchemaObject[]> {
    return $Call.ByID(2131088434, connectionID, database, schema).then(($result: any) => {
        return $$createType4($result);
    });
}

export function MigrateTableData(req: $models.DataMigrationRequest): $CancellablePromise<$models.DataMigrationResult> {
    return $Call.ByID(3157894491, req).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * PreviewInsertRowsSQL 生成与 InsertRows 语义接近的 INSERT 语句（展示用字符串字面量已按方言转义）。
 */
export function PreviewInsertRowsSQL(req: $models.PreviewInsertRowsRequest): $CancellablePromise<$models.InsertRowsSQLPreviewResponse> {
    return $Call.ByID(2443741732, req).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * PreviewUpdateRowsSQL 生成与 UpdateRows 语义一致的 UPDATE 语句（展示用字符串字面量已按方言转义）。
 */
export function PreviewUpdateRowsSQL(req: $models.UpdateRowsRequest): $CancellablePromise<$models.UpdateRowsSQLPreviewResponse> {
    return $Call.ByID(418193440, req).then(($result: any) => {
        return $$createType7($result);
    });
}

export function QuerySQLResultPage(req: $models.SQLResultPageRequest): $CancellablePromise<$models.QueryResultPage> {
    return $Call.ByID(2193096934, req).then(($result: any) => {
        return $$createType8($result);
    });
}

export function QueryTablePage(req: $models.TableQueryRequest): $CancellablePromise<$models.QueryResultPage> {
    return $Call.ByID(2696123903, req).then(($result: any) => {
        return $$createType8($result);
    });
}

export function StartDataMigration(req: $models.DataMigrationBatchRequest): $CancellablePromise<$models.DataMigrationJobSnapshot> {
    return $Call.ByID(1188566404, req).then(($result: any) => {
        return $$createType1($result);
    });
}

export function UpdateRows(req: $models.UpdateRowsRequest): $CancellablePromise<$models.SQLExecutionResult> {
    return $Call.ByID(3426811544, req).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.SQLExecutionResult.createFrom;
const $$createType1 = $models.DataMigrationJobSnapshot.createFrom;
const $$createType2 = $models.TableSchema.createFrom;
const $$createType3 = $models.SchemaObject.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.DataMigrationResult.createFrom;
const $$createType6 = $models.InsertRowsSQLPreviewResponse.createFrom;
const $$createType7 = $models.UpdateRowsSQLPreviewResponse.createFrom;
const $$createType8 = $models.QueryResultPage.createFrom;
