// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CancelRunningQuery(): $CancellablePromise<void> {
    return $Call.ByID(3091379923);
}

export function DeleteRows(req: $models.DeleteRowsRequest): $CancellablePromise<$models.SQLExecutionResult> {
    return $Call.ByID(1246682378, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ExecuteSQL(req: $models.ExecuteSQLRequest): $CancellablePromise<$models.SQLExecutionResult> {
    return $Call.ByID(1085282957, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ExplainSQL(req: $models.ExplainSQLRequest): $CancellablePromise<$models.SQLExecutionResult> {
    return $Call.ByID(3388748133, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function InsertRows(req: $models.InsertRowsRequest): $CancellablePromise<$models.SQLExecutionResult> {
    return $Call.ByID(2045419812, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ListDatabases(connectionID: string): $CancellablePromise<$models.SchemaObject[]> {
    return $Call.ByID(4087710774, connectionID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListIndexes(connectionID: string, database: string, schema: string, table: string): $CancellablePromise<$models.SchemaObject[]> {
    return $Call.ByID(3901981548, connectionID, database, schema, table).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListSchemas(connectionID: string, database: string): $CancellablePromise<$models.SchemaObject[]> {
    return $Call.ByID(2893177596, connectionID, database).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListTables(connectionID: string, database: string, schema: string): $CancellablePromise<$models.SchemaObject[]> {
    return $Call.ByID(4175186377, connectionID, database, schema).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListViews(connectionID: string, database: string, schema: string): $CancellablePromise<$models.SchemaObject[]> {
    return $Call.ByID(2131088434, connectionID, database, schema).then(($result: any) => {
        return $$createType2($result);
    });
}

export function QueryTablePage(req: $models.TableQueryRequest): $CancellablePromise<$models.QueryResultPage> {
    return $Call.ByID(2696123903, req).then(($result: any) => {
        return $$createType3($result);
    });
}

export function UpdateRows(req: $models.UpdateRowsRequest): $CancellablePromise<$models.SQLExecutionResult> {
    return $Call.ByID(3426811544, req).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.SQLExecutionResult.createFrom;
const $$createType1 = $models.SchemaObject.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.QueryResultPage.createFrom;
