// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../time/models.js";

/**
 * AssistRequest / AssistResponse 与 chat.AssistService 对齐，供 Wails 暴露给前端。
 */
export class AssistRequest {
    "dialect": string;
    "inputText": string;
    "selectedText": string;
    "databaseName": string;
    "connectionId"?: string;

    /** Creates a new AssistRequest instance. */
    constructor($$source: Partial<AssistRequest> = {}) {
        if (!("dialect" in $$source)) {
            this["dialect"] = "";
        }
        if (!("inputText" in $$source)) {
            this["inputText"] = "";
        }
        if (!("selectedText" in $$source)) {
            this["selectedText"] = "";
        }
        if (!("databaseName" in $$source)) {
            this["databaseName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssistRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): AssistRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AssistRequest($$parsedSource as Partial<AssistRequest>);
    }
}

export class AssistResponse {
    "intent": string;
    "type": string;
    "content": string;
    "explanation"?: string;
    "relevantTables"?: string[];
    "reason"?: string;

    /** Creates a new AssistResponse instance. */
    constructor($$source: Partial<AssistResponse> = {}) {
        if (!("intent" in $$source)) {
            this["intent"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssistResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): AssistResponse {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("relevantTables" in $$parsedSource) {
            $$parsedSource["relevantTables"] = $$createField4_0($$parsedSource["relevantTables"]);
        }
        return new AssistResponse($$parsedSource as Partial<AssistResponse>);
    }
}

export class BackgroundTask {
    "id": string;
    "kind": string;
    "status": string;
    "message": string;
    "logs": string[];
    "startedAt": time$0.Time;
    "endedAt": time$0.Time;

    /** Creates a new BackgroundTask instance. */
    constructor($$source: Partial<BackgroundTask> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("logs" in $$source)) {
            this["logs"] = [];
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = null;
        }
        if (!("endedAt" in $$source)) {
            this["endedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackgroundTask instance from a string or object.
     */
    static createFrom($$source: any = {}): BackgroundTask {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("logs" in $$parsedSource) {
            $$parsedSource["logs"] = $$createField4_0($$parsedSource["logs"]);
        }
        return new BackgroundTask($$parsedSource as Partial<BackgroundTask>);
    }
}

export class CancelRunningQueryRequest {
    "requestId": string;

    /** Creates a new CancelRunningQueryRequest instance. */
    constructor($$source: Partial<CancelRunningQueryRequest> = {}) {
        if (!("requestId" in $$source)) {
            this["requestId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CancelRunningQueryRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CancelRunningQueryRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CancelRunningQueryRequest($$parsedSource as Partial<CancelRunningQueryRequest>);
    }
}

export class ConnectionMeta {
    "id": string;
    "groupId": string;
    "name": string;
    "driver": string;
    "host": string;
    "port": number;
    "user": string;
    "defaultDb": string;
    "sslMode": string;
    "sshTunnel": boolean;
    "tags": string[];
    "readOnlyFlag": boolean;
    "favorite": boolean;
    "lastHealthCheckAt"?: time$0.Time | null;
    "lastHealthCheckOk": boolean;
    "lastHealthCheckError"?: string;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new ConnectionMeta instance. */
    constructor($$source: Partial<ConnectionMeta> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("groupId" in $$source)) {
            this["groupId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("driver" in $$source)) {
            this["driver"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("defaultDb" in $$source)) {
            this["defaultDb"] = "";
        }
        if (!("sslMode" in $$source)) {
            this["sslMode"] = "";
        }
        if (!("sshTunnel" in $$source)) {
            this["sshTunnel"] = false;
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("readOnlyFlag" in $$source)) {
            this["readOnlyFlag"] = false;
        }
        if (!("favorite" in $$source)) {
            this["favorite"] = false;
        }
        if (!("lastHealthCheckOk" in $$source)) {
            this["lastHealthCheckOk"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionMeta {
        const $$createField10_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField10_0($$parsedSource["tags"]);
        }
        return new ConnectionMeta($$parsedSource as Partial<ConnectionMeta>);
    }
}

export class ConnectionUpsertRequest {
    "groupId": string;
    "name": string;
    "driver": string;
    "host": string;
    "port": number;
    "user": string;
    "password": string;
    "defaultDb": string;
    "sslMode": string;
    "sshTunnel": boolean;
    "tags": string[];
    "readOnlyFlag": boolean;
    "favorite": boolean;

    /** Creates a new ConnectionUpsertRequest instance. */
    constructor($$source: Partial<ConnectionUpsertRequest> = {}) {
        if (!("groupId" in $$source)) {
            this["groupId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("driver" in $$source)) {
            this["driver"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("defaultDb" in $$source)) {
            this["defaultDb"] = "";
        }
        if (!("sslMode" in $$source)) {
            this["sslMode"] = "";
        }
        if (!("sshTunnel" in $$source)) {
            this["sshTunnel"] = false;
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("readOnlyFlag" in $$source)) {
            this["readOnlyFlag"] = false;
        }
        if (!("favorite" in $$source)) {
            this["favorite"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionUpsertRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionUpsertRequest {
        const $$createField10_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField10_0($$parsedSource["tags"]);
        }
        return new ConnectionUpsertRequest($$parsedSource as Partial<ConnectionUpsertRequest>);
    }
}

export class DataMigrationBatchRequest {
    "sourceConnectionId": string;
    "sourceDatabase": string;
    "sourceSchema": string;
    "sourceTables": string[];
    "targetConnectionId": string;
    "targetDatabase": string;
    "targetSchema": string;
    "truncateTarget": boolean;
    "workerCount": number;
    "batchSize": number;

    /** Creates a new DataMigrationBatchRequest instance. */
    constructor($$source: Partial<DataMigrationBatchRequest> = {}) {
        if (!("sourceConnectionId" in $$source)) {
            this["sourceConnectionId"] = "";
        }
        if (!("sourceDatabase" in $$source)) {
            this["sourceDatabase"] = "";
        }
        if (!("sourceSchema" in $$source)) {
            this["sourceSchema"] = "";
        }
        if (!("sourceTables" in $$source)) {
            this["sourceTables"] = [];
        }
        if (!("targetConnectionId" in $$source)) {
            this["targetConnectionId"] = "";
        }
        if (!("targetDatabase" in $$source)) {
            this["targetDatabase"] = "";
        }
        if (!("targetSchema" in $$source)) {
            this["targetSchema"] = "";
        }
        if (!("truncateTarget" in $$source)) {
            this["truncateTarget"] = false;
        }
        if (!("workerCount" in $$source)) {
            this["workerCount"] = 0;
        }
        if (!("batchSize" in $$source)) {
            this["batchSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DataMigrationBatchRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DataMigrationBatchRequest {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sourceTables" in $$parsedSource) {
            $$parsedSource["sourceTables"] = $$createField3_0($$parsedSource["sourceTables"]);
        }
        return new DataMigrationBatchRequest($$parsedSource as Partial<DataMigrationBatchRequest>);
    }
}

export class DataMigrationJobSnapshot {
    "jobId": string;
    "status": string;
    "workerCount": number;
    "batchSize": number;
    "total": number;
    "pending": number;
    "running": number;
    "success": number;
    "failed": number;
    "tables": DataMigrationTableStatus[];
    "startedAt": time$0.Time;
    "endedAt": time$0.Time;
    "message": string;

    /** Creates a new DataMigrationJobSnapshot instance. */
    constructor($$source: Partial<DataMigrationJobSnapshot> = {}) {
        if (!("jobId" in $$source)) {
            this["jobId"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("workerCount" in $$source)) {
            this["workerCount"] = 0;
        }
        if (!("batchSize" in $$source)) {
            this["batchSize"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("pending" in $$source)) {
            this["pending"] = 0;
        }
        if (!("running" in $$source)) {
            this["running"] = 0;
        }
        if (!("success" in $$source)) {
            this["success"] = 0;
        }
        if (!("failed" in $$source)) {
            this["failed"] = 0;
        }
        if (!("tables" in $$source)) {
            this["tables"] = [];
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = null;
        }
        if (!("endedAt" in $$source)) {
            this["endedAt"] = null;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DataMigrationJobSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): DataMigrationJobSnapshot {
        const $$createField9_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tables" in $$parsedSource) {
            $$parsedSource["tables"] = $$createField9_0($$parsedSource["tables"]);
        }
        return new DataMigrationJobSnapshot($$parsedSource as Partial<DataMigrationJobSnapshot>);
    }
}

export class DataMigrationRequest {
    "sourceConnectionId": string;
    "sourceDatabase": string;
    "sourceSchema": string;
    "sourceTable": string;
    "targetConnectionId": string;
    "targetDatabase": string;
    "targetSchema": string;
    "targetTable": string;
    "truncateTarget": boolean;
    "batchSize": number;

    /** Creates a new DataMigrationRequest instance. */
    constructor($$source: Partial<DataMigrationRequest> = {}) {
        if (!("sourceConnectionId" in $$source)) {
            this["sourceConnectionId"] = "";
        }
        if (!("sourceDatabase" in $$source)) {
            this["sourceDatabase"] = "";
        }
        if (!("sourceSchema" in $$source)) {
            this["sourceSchema"] = "";
        }
        if (!("sourceTable" in $$source)) {
            this["sourceTable"] = "";
        }
        if (!("targetConnectionId" in $$source)) {
            this["targetConnectionId"] = "";
        }
        if (!("targetDatabase" in $$source)) {
            this["targetDatabase"] = "";
        }
        if (!("targetSchema" in $$source)) {
            this["targetSchema"] = "";
        }
        if (!("targetTable" in $$source)) {
            this["targetTable"] = "";
        }
        if (!("truncateTarget" in $$source)) {
            this["truncateTarget"] = false;
        }
        if (!("batchSize" in $$source)) {
            this["batchSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DataMigrationRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DataMigrationRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DataMigrationRequest($$parsedSource as Partial<DataMigrationRequest>);
    }
}

export class DataMigrationResult {
    "migratedRows": number;
    "message": string;

    /** Creates a new DataMigrationResult instance. */
    constructor($$source: Partial<DataMigrationResult> = {}) {
        if (!("migratedRows" in $$source)) {
            this["migratedRows"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DataMigrationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DataMigrationResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DataMigrationResult($$parsedSource as Partial<DataMigrationResult>);
    }
}

export class DataMigrationTableStatus {
    "table": string;
    "targetTable": string;
    "status": string;
    "migratedRows": number;
    "message": string;
    "error": string;
    "startedAt": time$0.Time;
    "endedAt": time$0.Time;

    /** Creates a new DataMigrationTableStatus instance. */
    constructor($$source: Partial<DataMigrationTableStatus> = {}) {
        if (!("table" in $$source)) {
            this["table"] = "";
        }
        if (!("targetTable" in $$source)) {
            this["targetTable"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("migratedRows" in $$source)) {
            this["migratedRows"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = null;
        }
        if (!("endedAt" in $$source)) {
            this["endedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DataMigrationTableStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): DataMigrationTableStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DataMigrationTableStatus($$parsedSource as Partial<DataMigrationTableStatus>);
    }
}

export class DeleteRowsRequest {
    "connectionId": string;
    "database": string;
    "schema": string;
    "table": string;
    "keyColumns": string[];
    "rows": { [_ in string]?: any }[];

    /** Creates a new DeleteRowsRequest instance. */
    constructor($$source: Partial<DeleteRowsRequest> = {}) {
        if (!("connectionId" in $$source)) {
            this["connectionId"] = "";
        }
        if (!("database" in $$source)) {
            this["database"] = "";
        }
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("table" in $$source)) {
            this["table"] = "";
        }
        if (!("keyColumns" in $$source)) {
            this["keyColumns"] = [];
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeleteRowsRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DeleteRowsRequest {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("keyColumns" in $$parsedSource) {
            $$parsedSource["keyColumns"] = $$createField4_0($$parsedSource["keyColumns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField5_0($$parsedSource["rows"]);
        }
        return new DeleteRowsRequest($$parsedSource as Partial<DeleteRowsRequest>);
    }
}

export class ExecuteSQLRequest {
    "connectionId": string;
    "database": string;
    "sql": string;
    "rowLimit": number;
    "timeoutMs": number;
    "mode": string;
    "requestId": string;

    /** Creates a new ExecuteSQLRequest instance. */
    constructor($$source: Partial<ExecuteSQLRequest> = {}) {
        if (!("connectionId" in $$source)) {
            this["connectionId"] = "";
        }
        if (!("database" in $$source)) {
            this["database"] = "";
        }
        if (!("sql" in $$source)) {
            this["sql"] = "";
        }
        if (!("rowLimit" in $$source)) {
            this["rowLimit"] = 0;
        }
        if (!("timeoutMs" in $$source)) {
            this["timeoutMs"] = 0;
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("requestId" in $$source)) {
            this["requestId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExecuteSQLRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ExecuteSQLRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExecuteSQLRequest($$parsedSource as Partial<ExecuteSQLRequest>);
    }
}

export class ExplainSQLRequest {
    "connectionId": string;
    "database": string;
    "sql": string;
    "requestId": string;

    /** Creates a new ExplainSQLRequest instance. */
    constructor($$source: Partial<ExplainSQLRequest> = {}) {
        if (!("connectionId" in $$source)) {
            this["connectionId"] = "";
        }
        if (!("database" in $$source)) {
            this["database"] = "";
        }
        if (!("sql" in $$source)) {
            this["sql"] = "";
        }
        if (!("requestId" in $$source)) {
            this["requestId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExplainSQLRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ExplainSQLRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExplainSQLRequest($$parsedSource as Partial<ExplainSQLRequest>);
    }
}

export class GroupCreateRequest {
    "name": string;
    "color": string;
    "icon": string;

    /** Creates a new GroupCreateRequest instance. */
    constructor($$source: Partial<GroupCreateRequest> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GroupCreateRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): GroupCreateRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GroupCreateRequest($$parsedSource as Partial<GroupCreateRequest>);
    }
}

export class GroupReorderRequest {
    "orderedIds": string[];

    /** Creates a new GroupReorderRequest instance. */
    constructor($$source: Partial<GroupReorderRequest> = {}) {
        if (!("orderedIds" in $$source)) {
            this["orderedIds"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GroupReorderRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): GroupReorderRequest {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("orderedIds" in $$parsedSource) {
            $$parsedSource["orderedIds"] = $$createField0_0($$parsedSource["orderedIds"]);
        }
        return new GroupReorderRequest($$parsedSource as Partial<GroupReorderRequest>);
    }
}

export class GroupUpdateRequest {
    "name": string;
    "color": string;
    "icon": string;

    /** Creates a new GroupUpdateRequest instance. */
    constructor($$source: Partial<GroupUpdateRequest> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GroupUpdateRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): GroupUpdateRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GroupUpdateRequest($$parsedSource as Partial<GroupUpdateRequest>);
    }
}

export class InsertRowsRequest {
    "connectionId": string;
    "database": string;
    "schema": string;
    "table": string;
    "rows": { [_ in string]?: any }[];

    /** Creates a new InsertRowsRequest instance. */
    constructor($$source: Partial<InsertRowsRequest> = {}) {
        if (!("connectionId" in $$source)) {
            this["connectionId"] = "";
        }
        if (!("database" in $$source)) {
            this["database"] = "";
        }
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("table" in $$source)) {
            this["table"] = "";
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InsertRowsRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): InsertRowsRequest {
        const $$createField4_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField4_0($$parsedSource["rows"]);
        }
        return new InsertRowsRequest($$parsedSource as Partial<InsertRowsRequest>);
    }
}

/**
 * InsertRowsSQLPreviewResponse 与 PreviewInsertRowsRequest 一致时生成的可展示 INSERT 文本（按方言转义字面量）。
 */
export class InsertRowsSQLPreviewResponse {
    "statements": string[];

    /** Creates a new InsertRowsSQLPreviewResponse instance. */
    constructor($$source: Partial<InsertRowsSQLPreviewResponse> = {}) {
        if (!("statements" in $$source)) {
            this["statements"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InsertRowsSQLPreviewResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): InsertRowsSQLPreviewResponse {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("statements" in $$parsedSource) {
            $$parsedSource["statements"] = $$createField0_0($$parsedSource["statements"]);
        }
        return new InsertRowsSQLPreviewResponse($$parsedSource as Partial<InsertRowsSQLPreviewResponse>);
    }
}

/**
 * PreviewInsertRowsRequest 用于生成可复制的 INSERT 预览语句。
 */
export class PreviewInsertRowsRequest {
    "connectionId": string;
    "database": string;
    "schema": string;
    "table": string;
    "columns": string[];
    "rows": { [_ in string]?: any }[];

    /** Creates a new PreviewInsertRowsRequest instance. */
    constructor($$source: Partial<PreviewInsertRowsRequest> = {}) {
        if (!("connectionId" in $$source)) {
            this["connectionId"] = "";
        }
        if (!("database" in $$source)) {
            this["database"] = "";
        }
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("table" in $$source)) {
            this["table"] = "";
        }
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreviewInsertRowsRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): PreviewInsertRowsRequest {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField4_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField5_0($$parsedSource["rows"]);
        }
        return new PreviewInsertRowsRequest($$parsedSource as Partial<PreviewInsertRowsRequest>);
    }
}

export class QueryResultPage {
    "columns": string[];
    "columnTypes"?: string[];
    "rows": { [_ in string]?: any }[];
    "total": number;
    "offset": number;
    "limit": number;
    "durationMs": number;

    /** Creates a new QueryResultPage instance. */
    constructor($$source: Partial<QueryResultPage> = {}) {
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryResultPage instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryResultPage {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("columnTypes" in $$parsedSource) {
            $$parsedSource["columnTypes"] = $$createField1_0($$parsedSource["columnTypes"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField2_0($$parsedSource["rows"]);
        }
        return new QueryResultPage($$parsedSource as Partial<QueryResultPage>);
    }
}

export class SQLExecutionResult {
    "columns"?: string[];

    /**
     * 与 columns 同序，驱动返回的 DatabaseTypeName（小写）
     */
    "columnTypes"?: string[];
    "rows"?: { [_ in string]?: any }[];
    "rowsAffected": number;
    "lastInsertId": number;
    "message": string;
    "truncated": boolean;
    "durationMs": number;
    "execLog"?: string[];

    /** Creates a new SQLExecutionResult instance. */
    constructor($$source: Partial<SQLExecutionResult> = {}) {
        if (!("rowsAffected" in $$source)) {
            this["rowsAffected"] = 0;
        }
        if (!("lastInsertId" in $$source)) {
            this["lastInsertId"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SQLExecutionResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SQLExecutionResult {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType4;
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("columnTypes" in $$parsedSource) {
            $$parsedSource["columnTypes"] = $$createField1_0($$parsedSource["columnTypes"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField2_0($$parsedSource["rows"]);
        }
        if ("execLog" in $$parsedSource) {
            $$parsedSource["execLog"] = $$createField8_0($$parsedSource["execLog"]);
        }
        return new SQLExecutionResult($$parsedSource as Partial<SQLExecutionResult>);
    }
}

export class SaveStudioSessionRequest {
    "groupId": string;
    "activeConnectionId": string;
    "tabs": StudioTabSnapshot[];

    /** Creates a new SaveStudioSessionRequest instance. */
    constructor($$source: Partial<SaveStudioSessionRequest> = {}) {
        if (!("groupId" in $$source)) {
            this["groupId"] = "";
        }
        if (!("activeConnectionId" in $$source)) {
            this["activeConnectionId"] = "";
        }
        if (!("tabs" in $$source)) {
            this["tabs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveStudioSessionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveStudioSessionRequest {
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tabs" in $$parsedSource) {
            $$parsedSource["tabs"] = $$createField2_0($$parsedSource["tabs"]);
        }
        return new SaveStudioSessionRequest($$parsedSource as Partial<SaveStudioSessionRequest>);
    }
}

export class SchemaObject {
    "name": string;

    /** Creates a new SchemaObject instance. */
    constructor($$source: Partial<SchemaObject> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchemaObject instance from a string or object.
     */
    static createFrom($$source: any = {}): SchemaObject {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SchemaObject($$parsedSource as Partial<SchemaObject>);
    }
}

export class Settings {
    /**
     * light, dark, system
     */
    "theme": string;

    /**
     * zh-CN, en-US
     */
    "language": string;

    /**
     * 自动保存
     */
    "autoSave": boolean;

    /**
     * 自动保存延迟（秒）
     */
    "autoSaveDelay": number;

    /**
     * 查询结果行数限制
     */
    "queryLimit": number;

    /**
     * 查询超时（毫秒）
     */
    "queryTimeout": number;

    /**
     * 执行前确认
     */
    "confirmBefore": boolean;

    /**
     * 编辑器字体大小
     */
    "fontSize": number;

    /**
     * 编辑器字体
     */
    "fontFamily": string;

    /**
     * 显示行号
     */
    "showLineNumbers": boolean;

    /**
     * 自动换行
     */
    "wordWrap": boolean;

    /**
     * 制表符宽度
     */
    "tabSize": number;

    /**
     * AI 配置
     * AI API Key
     */
    "aiApiKey": string;

    /**
     * AI API URL
     */
    "aiApiUrl": string;

    /**
     * AI Model Name
     */
    "aiModelName": string;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("autoSave" in $$source)) {
            this["autoSave"] = false;
        }
        if (!("autoSaveDelay" in $$source)) {
            this["autoSaveDelay"] = 0;
        }
        if (!("queryLimit" in $$source)) {
            this["queryLimit"] = 0;
        }
        if (!("queryTimeout" in $$source)) {
            this["queryTimeout"] = 0;
        }
        if (!("confirmBefore" in $$source)) {
            this["confirmBefore"] = false;
        }
        if (!("fontSize" in $$source)) {
            this["fontSize"] = 0;
        }
        if (!("fontFamily" in $$source)) {
            this["fontFamily"] = "";
        }
        if (!("showLineNumbers" in $$source)) {
            this["showLineNumbers"] = false;
        }
        if (!("wordWrap" in $$source)) {
            this["wordWrap"] = false;
        }
        if (!("tabSize" in $$source)) {
            this["tabSize"] = 0;
        }
        if (!("aiApiKey" in $$source)) {
            this["aiApiKey"] = "";
        }
        if (!("aiApiUrl" in $$source)) {
            this["aiApiUrl"] = "";
        }
        if (!("aiModelName" in $$source)) {
            this["aiModelName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

export class StudioSessionSnapshot {
    "groupId": string;
    "activeConnectionId": string;
    "tabs": StudioTabSnapshot[];
    "updatedAt": time$0.Time;

    /** Creates a new StudioSessionSnapshot instance. */
    constructor($$source: Partial<StudioSessionSnapshot> = {}) {
        if (!("groupId" in $$source)) {
            this["groupId"] = "";
        }
        if (!("activeConnectionId" in $$source)) {
            this["activeConnectionId"] = "";
        }
        if (!("tabs" in $$source)) {
            this["tabs"] = [];
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StudioSessionSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): StudioSessionSnapshot {
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tabs" in $$parsedSource) {
            $$parsedSource["tabs"] = $$createField2_0($$parsedSource["tabs"]);
        }
        return new StudioSessionSnapshot($$parsedSource as Partial<StudioSessionSnapshot>);
    }
}

export class StudioTabSnapshot {
    "id": string;
    "title": string;
    "sql": string;
    "connectionId": string;
    "contextDb": string;
    "contextTable": string;

    /** Creates a new StudioTabSnapshot instance. */
    constructor($$source: Partial<StudioTabSnapshot> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("sql" in $$source)) {
            this["sql"] = "";
        }
        if (!("connectionId" in $$source)) {
            this["connectionId"] = "";
        }
        if (!("contextDb" in $$source)) {
            this["contextDb"] = "";
        }
        if (!("contextTable" in $$source)) {
            this["contextTable"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StudioTabSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): StudioTabSnapshot {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StudioTabSnapshot($$parsedSource as Partial<StudioTabSnapshot>);
    }
}

/**
 * Table schema related types
 */
export class TableColumnSchema {
    "name": string;
    "type": string;
    "nullable": boolean;
    "defaultValue": string;
    "primaryKey": boolean;
    "unique": boolean;
    "autoIncrement": boolean;
    "comment": string;

    /** Creates a new TableColumnSchema instance. */
    constructor($$source: Partial<TableColumnSchema> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("nullable" in $$source)) {
            this["nullable"] = false;
        }
        if (!("defaultValue" in $$source)) {
            this["defaultValue"] = "";
        }
        if (!("primaryKey" in $$source)) {
            this["primaryKey"] = false;
        }
        if (!("unique" in $$source)) {
            this["unique"] = false;
        }
        if (!("autoIncrement" in $$source)) {
            this["autoIncrement"] = false;
        }
        if (!("comment" in $$source)) {
            this["comment"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableColumnSchema instance from a string or object.
     */
    static createFrom($$source: any = {}): TableColumnSchema {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TableColumnSchema($$parsedSource as Partial<TableColumnSchema>);
    }
}

export class TableQueryRequest {
    "connectionId": string;
    "database": string;
    "schema": string;
    "table": string;
    "offset": number;
    "limit": number;
    "orderBy": string;
    "orderDesc": boolean;

    /** Creates a new TableQueryRequest instance. */
    constructor($$source: Partial<TableQueryRequest> = {}) {
        if (!("connectionId" in $$source)) {
            this["connectionId"] = "";
        }
        if (!("database" in $$source)) {
            this["database"] = "";
        }
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("table" in $$source)) {
            this["table"] = "";
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }
        if (!("orderBy" in $$source)) {
            this["orderBy"] = "";
        }
        if (!("orderDesc" in $$source)) {
            this["orderDesc"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableQueryRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): TableQueryRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TableQueryRequest($$parsedSource as Partial<TableQueryRequest>);
    }
}

export class TableSchema {
    "name": string;
    "database": string;
    "schema": string;
    "engine": string;
    "charset": string;
    "collation": string;
    "comment": string;
    "columns": TableColumnSchema[];
    "primaryKey": string[];

    /** Creates a new TableSchema instance. */
    constructor($$source: Partial<TableSchema> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("database" in $$source)) {
            this["database"] = "";
        }
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("engine" in $$source)) {
            this["engine"] = "";
        }
        if (!("charset" in $$source)) {
            this["charset"] = "";
        }
        if (!("collation" in $$source)) {
            this["collation"] = "";
        }
        if (!("comment" in $$source)) {
            this["comment"] = "";
        }
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("primaryKey" in $$source)) {
            this["primaryKey"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableSchema instance from a string or object.
     */
    static createFrom($$source: any = {}): TableSchema {
        const $$createField7_0 = $$createType8;
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField7_0($$parsedSource["columns"]);
        }
        if ("primaryKey" in $$parsedSource) {
            $$parsedSource["primaryKey"] = $$createField8_0($$parsedSource["primaryKey"]);
        }
        return new TableSchema($$parsedSource as Partial<TableSchema>);
    }
}

export class TableSchemaRequest {
    "connectionId": string;
    "database": string;
    "schema": string;
    "table": string;

    /** Creates a new TableSchemaRequest instance. */
    constructor($$source: Partial<TableSchemaRequest> = {}) {
        if (!("connectionId" in $$source)) {
            this["connectionId"] = "";
        }
        if (!("database" in $$source)) {
            this["database"] = "";
        }
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("table" in $$source)) {
            this["table"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableSchemaRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): TableSchemaRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TableSchemaRequest($$parsedSource as Partial<TableSchemaRequest>);
    }
}

export class UpdateRowsRequest {
    "connectionId": string;
    "database": string;
    "schema": string;
    "table": string;
    "keyColumns": string[];
    "rows": { [_ in string]?: any }[];

    /** Creates a new UpdateRowsRequest instance. */
    constructor($$source: Partial<UpdateRowsRequest> = {}) {
        if (!("connectionId" in $$source)) {
            this["connectionId"] = "";
        }
        if (!("database" in $$source)) {
            this["database"] = "";
        }
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("table" in $$source)) {
            this["table"] = "";
        }
        if (!("keyColumns" in $$source)) {
            this["keyColumns"] = [];
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateRowsRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateRowsRequest {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("keyColumns" in $$parsedSource) {
            $$parsedSource["keyColumns"] = $$createField4_0($$parsedSource["keyColumns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField5_0($$parsedSource["rows"]);
        }
        return new UpdateRowsRequest($$parsedSource as Partial<UpdateRowsRequest>);
    }
}

/**
 * UpdateRowsSQLPreviewResponse 与 UpdateRows 请求一致时生成的可展示 UPDATE 文本（按方言转义字面量）。
 */
export class UpdateRowsSQLPreviewResponse {
    "statements": string[];

    /** Creates a new UpdateRowsSQLPreviewResponse instance. */
    constructor($$source: Partial<UpdateRowsSQLPreviewResponse> = {}) {
        if (!("statements" in $$source)) {
            this["statements"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateRowsSQLPreviewResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateRowsSQLPreviewResponse {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("statements" in $$parsedSource) {
            $$parsedSource["statements"] = $$createField0_0($$parsedSource["statements"]);
        }
        return new UpdateRowsSQLPreviewResponse($$parsedSource as Partial<UpdateRowsSQLPreviewResponse>);
    }
}

export class VaultStatus {
    "hasMasterPassword": boolean;
    "unlocked": boolean;

    /** Creates a new VaultStatus instance. */
    constructor($$source: Partial<VaultStatus> = {}) {
        if (!("hasMasterPassword" in $$source)) {
            this["hasMasterPassword"] = false;
        }
        if (!("unlocked" in $$source)) {
            this["unlocked"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VaultStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): VaultStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VaultStatus($$parsedSource as Partial<VaultStatus>);
    }
}

export class WorkspaceGroup {
    "id": string;
    "name": string;
    "color": string;
    "icon": string;
    "order": number;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new WorkspaceGroup instance. */
    constructor($$source: Partial<WorkspaceGroup> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("order" in $$source)) {
            this["order"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceGroup {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceGroup($$parsedSource as Partial<WorkspaceGroup>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = DataMigrationTableStatus.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = StudioTabSnapshot.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = TableColumnSchema.createFrom;
const $$createType8 = $Create.Array($$createType7);
