// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ChangeMasterPassword($0: string, $1: string): $CancellablePromise<void> {
    return $Call.ByID(1066622074, $0, $1);
}

export function DeleteConnectionSecret(connectionID: string): $CancellablePromise<void> {
    return $Call.ByID(1448204774, connectionID);
}

export function GetConnectionSecret(connectionID: string): $CancellablePromise<string> {
    return $Call.ByID(3454247751, connectionID);
}

export function GetVaultStatus(): $CancellablePromise<$models.VaultStatus> {
    return $Call.ByID(2790318051).then(($result: any) => {
        return $$createType0($result);
    });
}

export function LockVault(): $CancellablePromise<void> {
    return $Call.ByID(561737262);
}

export function RequireUnlocked(): $CancellablePromise<void> {
    return $Call.ByID(1101180993);
}

export function SetConnectionSecret(connectionID: string, secret: string): $CancellablePromise<void> {
    return $Call.ByID(2604279859, connectionID, secret);
}

export function SetMasterPassword($0: string): $CancellablePromise<void> {
    return $Call.ByID(3738809308, $0);
}

export function UnlockVault($0: string): $CancellablePromise<void> {
    return $Call.ByID(3804056383, $0);
}

// Private type creation functions
const $$createType0 = $models.VaultStatus.createFrom;
