// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetAIConfig 获取 AI 配置
 */
export function GetAIConfig(): $CancellablePromise<[string, string, string]> {
    return $Call.ByID(2143829760);
}

export function GetSettingPath(): $CancellablePromise<string> {
    return $Call.ByID(1748520051);
}

export function GetSettings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(3034808949).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ResetSettings(): $CancellablePromise<void> {
    return $Call.ByID(2916436918);
}

/**
 * SaveAIConfig 保存 AI 配置
 */
export function SaveAIConfig(apiKey: string, apiUrl: string, modelName: string): $CancellablePromise<void> {
    return $Call.ByID(3896736401, apiKey, apiUrl, modelName);
}

export function UpdateSettings(newSettings: $models.Settings): $CancellablePromise<void> {
    return $Call.ByID(2846770304, newSettings);
}

// Private type creation functions
const $$createType0 = $models.Settings.createFrom;
