// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * FocusMainWindow 聚焦连接管理主窗口（名称为 main）。
 */
export function FocusMainWindow(): $CancellablePromise<void> {
    return $Call.ByID(4185161028);
}

export function OpenGroupWindow(groupID: string): $CancellablePromise<void> {
    return $Call.ByID(4132042458, groupID);
}
