// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateConnection(req: $models.ConnectionUpsertRequest): $CancellablePromise<$models.ConnectionMeta> {
    return $Call.ByID(2714666428, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CreateGroup(req: $models.GroupCreateRequest): $CancellablePromise<$models.WorkspaceGroup> {
    return $Call.ByID(1985283839, req).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteConnection(connectionID: string): $CancellablePromise<void> {
    return $Call.ByID(954343939, connectionID);
}

export function DeleteGroup(groupID: string): $CancellablePromise<void> {
    return $Call.ByID(4044524138, groupID);
}

export function GetStudioSession(groupID: string): $CancellablePromise<$models.StudioSessionSnapshot> {
    return $Call.ByID(1882268046, groupID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListGroupConnections(groupID: string): $CancellablePromise<$models.ConnectionMeta[]> {
    return $Call.ByID(1344559632, groupID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ListGroups(): $CancellablePromise<$models.WorkspaceGroup[]> {
    return $Call.ByID(569968640).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ListRecentGroupIDs(): $CancellablePromise<string[]> {
    return $Call.ByID(1436877508).then(($result: any) => {
        return $$createType5($result);
    });
}

export function MarkGroupOpened(groupID: string): $CancellablePromise<void> {
    return $Call.ByID(1264728841, groupID);
}

export function ReorderGroups(req: $models.GroupReorderRequest): $CancellablePromise<void> {
    return $Call.ByID(1940444139, req);
}

export function SaveStudioSession(req: $models.SaveStudioSessionRequest): $CancellablePromise<void> {
    return $Call.ByID(3830207789, req);
}

export function SetConnectionFavorite(connectionID: string, favorite: boolean): $CancellablePromise<$models.ConnectionMeta> {
    return $Call.ByID(2904109228, connectionID, favorite).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SetConnectionTags(connectionID: string, tags: string[]): $CancellablePromise<$models.ConnectionMeta> {
    return $Call.ByID(3211045961, connectionID, tags).then(($result: any) => {
        return $$createType0($result);
    });
}

export function TestConnection(connectionID: string): $CancellablePromise<string> {
    return $Call.ByID(3962028284, connectionID);
}

export function UpdateConnection(connectionID: string, req: $models.ConnectionUpsertRequest): $CancellablePromise<$models.ConnectionMeta> {
    return $Call.ByID(960943781, connectionID, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function UpdateGroup(groupID: string, req: $models.GroupUpdateRequest): $CancellablePromise<$models.WorkspaceGroup> {
    return $Call.ByID(2920214464, groupID, req).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ConnectionMeta.createFrom;
const $$createType1 = $models.WorkspaceGroup.createFrom;
const $$createType2 = $models.StudioSessionSnapshot.createFrom;
const $$createType3 = $Create.Array($$createType0);
const $$createType4 = $Create.Array($$createType1);
const $$createType5 = $Create.Array($Create.Any);
